/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cpk;

import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

public class App {
    private static final Map<String, Supplier<Spike>> spikes =
        Map.of("first", First::new,
                "speak", Speak::new,
                "speak2", Speak2::new,
                "deck", DeckOfCardsInterview::new);

    private static final Supplier<Spike> current = spikes.get("deck");

    public static void main(String[] args) throws Exception {
        Optional.of(args)
            .filter(a -> a.length > 0)
            .map(a -> a[0])
            .map(spikes::get)
            .orElse(current)
            .get()
            .run(new Args(args));
    }
}
